language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key: a125baed-4f42-4371-9e50-b9561a2526f6 # This token is no longer valid. Update to latest heroku auth token typing "heroku auth:token" in the CLI and copying and pasting it here.
  app: cryptic-everglades-24336
