language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: AJxJOdnw6R/41yXZf4Tzpxq7mXBC6R+mZjCy1SpghExAyTwGrsWIjt+4BvcIypjlMnhjvUTTD/LuXOzr9PSEvumodDdoaLV2w+R1w/2pB1tRMADdGzLwOPQBts8tE5UnujlptPgmwjN1Cr7g/9ik//fiKGgMeOQaKpKGQURssZte5EbooClYwYHa9z2+6/CEmER2pwnDfzWhz0BwZ2Fe80y/rU5qBWztXnOfcOn/MrMrXpauhLrI9g0Kg/3HOepaGATbz4LRZSemWlYauh2Ty5Pwz5w3sfvHCZLrxlUo+UCDccxtZWCU4V25gfmzFTwP31pJmgQ9cl1vaTnf7GPEtp6Vc9OYqztGeC7yhl+PVAoWMjA/RQrN2an0+j2cOaeL10k3cDir8JiIJBNYpFJ267RuOVHe3crB8Q5uOMeWM1RKs3gXKAAKOSwoC1j5aS0N3eBvtk8WeGDWJPpP7ymo/AE92dS46Uvn2L8pdzc9l3BGM1e0xd1VtnuFd3pC54gJEc8jhci+lloDLmGbzPtFz1vLa4hAh3iylTCWDcGikWrRrCstKG5f9KwIV9XvfF2BOAwBDek3crsAHx9qvGJc151og9RUaNN34D7RRDTKGOVA/mBNPkrUROzUHnWzL+RK2j2/HSELVg6xowLyRr43Nh1lp3NFJilxEP/GHCoou+U=
  app: cryptic-everglades-24336
