language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: gS9m+xiy+mQug99db7LvzuqkWh82j+D/RR12Wyb+RFcckdefPbxg94Krf58vZioBRukYTWvF81w69JO7eSOQ5xITvGFbJg9tIb29J6knjiTW81rCBRWjcGcU2RBsx+hwUqEf0VNBkpWoZT8kJU+O8XJSWRQ7Y2G+h65bqlTa/L/EhWtVfRSOt/PN8o/RFL0B0uTDcYP6fwMXpsODwacykB9v0qRtwYzraGtH1Dc7F2HJwO3YIYsnAerNEl7Y1X0kfMejGb43uRGvUBk5koX7LuGlqSNbwF1Ph7MTep6U7zb02+OwjkKhyElOa93q4OUobN9/SFuwjLvqcuGYl7worzvccHE9eU+mtHsHRNBLPAgro8ZX8+qx6LVPAknHDHsjXQcXrk5JFVO52Wrz2W/8QwiYJtSEB/tyZnhJwdjqkAiQSNCrR7sCBBuFqvEEOyrfsGhZPoDNcKLoIKGAf7sFAjkxGJ1E9OREnCtPZkbORMnqhssAVGswPIZ6I5sqO55v4rZI0lJY2T/2ypta+cY1XuiqWDMxumH3MDpFWU43BbriFEXR5oldsnRM3YoK6fIH1sOga6l9sEZ/3ES9kAVxoduEcEoQZWhVVwRu5zdERsykikfcRM/6wj8/hwIudgqGFZx8Uj2SNuEORw8rlDOQ+Sc/RH8XrbsW3dcwbopAZgo=
  app: cryptic-everglades-24336
